services:
  madplanen:
    image: madplanen:latest
    container_name: madplanen
    environment:
      DB_HOST: postgresql
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: madplanen
      DB_SCHEMA: madplanen
      DB_PORT: 5432
    ports:
      - 8080:8080
    depends_on:
      postgresql:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: http://localhost:8080/madplanen/openapi.yaml
    ports:
      - 8081:8080

  postgresql:
    image: postgres:18.1-alpine3.23
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U madplanen-admin -d madplanen" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: false
    ports:
      - 8082:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgresql:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data: